### PR TITLE
Create job posting

### PR DESCRIPTION
**Pull request by jamessnguyenn**
These changes included the follow:
- created "add a job" page for recruiters to add a job
- changed some ids with the jobseeker sign up
- added character counter to recruiter sign up
- modified recruiter dashboard and nav bar so that it routes to add a job page
- add svg to recruiter dashboard when there are no jobs
- modified backend schema of job posters

### CODE REVIEW

**Review by Christophervtran92 — CHANGES_REQUESTED** [review]
I was able to navigate to the recruiter dashboard, create a new job, and the new job showed up just fine. I was able to sign up a new recruiter as well just fine and log it in. An issue popped up when I made a new job seeker (_id: "618d585b6948161cbb5c6a48") and added them to the new job listing (_id: "618d577d6948161cbb5c6a44") and then logged into the recruiter (_id: "618d57386948161cbb5c6a41") associated with the job posting. There was an unexpected error that seemed to be stemming from the applicant cards and their display of their experiences.

Capture
.

**Comment by jamessnguyenn** [comment]
So turns out the problem was because I passed in experiences[1] when it should be experiences[0]. I have made the changes and the bug should be fixed.

image

**Review by Christophervtran92 — APPROVED** [review]
Tested the dashboard again and now it's working. Some minor things I noticed with the title cards though is that Experiences and Websites are jammed together on the same line and education places "degree" after their education so you end up with "Degree degree". Also, a bit nitpicky, on the addJob page it should probably be "Be sure to be as detailed as possible". Otherwise it all seems to be good to go.

Capture
e"
Capture

**Comment by jamessnguyenn** [comment]
Sounds good. I will address these errors in a future pull request.

**Pull request merged**
